services:
  affine-todo-bridge:
    build:
      context: https://github.com/david-stefan-hermann/n8n-Workflows.git#master:affine-todo-bridge
    container_name: affine-todo-bridge
    restart: unless-stopped
    env_file: .env
    ports:
      - "30170:3000"
    networks:
      - ix-n8n_ix-internal-n8n-net

networks:
  ix-n8n_ix-internal-n8n-net:
    external: true
